[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ImageBinarization = "cbc4b850-ae4b-5111-9e64-df94c024a13d"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"