name = "ImageMorphology"
uuid = "787d08f9-d448-5407-9aad-5290dd7ab264"
version = "0.2.12"

[deps]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"

[compat]
Documenter = "0.24, 0.25"
ImageCore = "0.9"
TiledIteration = "0.2, 0.3"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "OffsetArrays", "Test"]
